[features]
seeds = false

[registry]
url = "localnet"

[provider]
cluster = "localnet"
wallet = "YOUR_WALLET_PATH"
[workspace]
members = ["program"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 /mnt/c/Users/User/Desktop/peer-guard-fork/mpl-candy-machine-peerguard/programs/candy-guard/tests/**/*.ts"
